version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: app-mysql
    working_dir: /etc/mysql
    volumes:
        - paymentdemo.mysql:/var/lib/mysql
        - ./database/conf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    ports:
        - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: app-webserver
    working_dir: /application
    volumes:
      - ./app:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - php-fpm

  php-fpm:
    build: phpdocker/php-fpm
    container_name: app-php-fpm
    working_dir: /application
    volumes:
      - ./app:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    links:
      - mysql
  
networks: 
  network-paymentdemo:
    external: true

volumes:
  paymentdemo.mysql: